swagger: "2.0"
info:
  version: "0.0.1"
  title: Eventol auth
  description: Eventol auth
# during dev, should point to your local machine
host: localhost:3000
# basePath prefixes all resource paths
basePath: /api
#
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /login:
    # binds a127 app logic to a route
    x-swagger-router-controller: user
    post:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: logIn
      parameters:
        - name: credentials
          in: body
          description: The credentials of the user
          required: true
          schema:
            $ref: '#/definitions/Credentials'
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
# complex objects have schema definitions
definitions:
  Credentials:
      properties:
        username:
          type: string
        password:
          type: string
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
