swagger: "2.0"
info:
  version: "0.0.1"
  title: Eventol auth
  description: Eventol auth
# during dev, should point to your local machine
host: localhost:3000
# basePath prefixes all resource paths
basePath: /api
#
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /signup:
    x-swagger-router-controller: signup
    post:
      operationId: signUp
      parameters:
          - name: user
            in: body
            description: The properties of the user
            required: true
            schema:
              $ref: '#/definitions/UserProperties'
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/JwtResponse'
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /login:
    x-swagger-router-controller: login
    post:
      description: Returns 'Hello' to the caller
      operationId: logIn
      parameters:
        - name: credentials
          in: body
          description: The credentials of the user
          required: true
          schema:
            $ref: '#/definitions/Credentials'
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/JwtResponse'
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
definitions:
  UserProperties:
      properties:
        username:
          type: string
        password:
          type: string
  Credentials:
      properties:
        username:
          type: string
        password:
          type: string
        email:
          type: string
  JwtResponse:
    required:
      - jwt
    properties:
      jwt:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
